server:
  port: 8081

spring:  application:    name: goliardia
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb    username: sa
    password: 
    schema:    - classpath:sql/schema.sql
    data:    - classpath:sql/data.sql
  h2:    console:      enabled: true
      path: /h2
mybatis:  configuration:    jdbc-type-for-null: null
    map-underscore-to-camel-case: true
  type-aliases-package: it.cenci.goliardia.dao
  
---   
spring:
  profiles: test
  datasource:
   driver-class-name: com.mysql.cj.jdbc.Driver
   url: jdbc:mysql://127.0.0.1:3306/goliardia?serverTimezone=UTC
   username: michele
   password: michele